# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET https://api.github.com/repos/2Pit/test/git/refs
Accept: application/vnd.github.v3+json
Authorization: token 147d2090ec01f251b04912916f14d4ce3646b5b7
###

GET https://api.github.com/repos/2Pit/test/git/trees/c8a490b678d1b78ba3e353ba27bb500a130cbcbb
Accept: application/vnd.github.v3+json
Authorization: token 147d2090ec01f251b04912916f14d4ce3646b5b7

###

GET https://api.github.com/repos/2Pit/test-2/git/commits/6ab55301aae7039a7bf00313a6f52aede3b8e8ae
Accept: application/vnd.github.v3+json
Authorization: token 147d2090ec01f251b04912916f14d4ce3646b5b7
###

PATCH https://api.github.com/repos/2Pit/test-2/git/refs/heads/master
Accept: application/vnd.github.v3+json
Authorization: token 147d2090ec01f251b04912916f14d4ce3646b5b7
Content-Type: application/json

{
  "sha": "6ab55301aae7039a7bf00313a6f52aede3b8e8ae",
  "force": true
}

###