POST http://0.0.0.0:8090/add
#host: smee.io
#Accept-Encoding: gzip, deflate
#user-agent: GitHub-Hookshot/d410879
content-type: application/json
#connection: close
accept: */*
x-github-event: installation
x-github-delivery: bef36880-be8d-11e9-9234-c8a65befea48
x-request-id: afa018dc-2d1a-453e-859e-cc8e4aadfa9c
x-forwarded-for: 140.82.115.9
#x-forwarded-proto: https
#x-forwarded-port: 443
#via: 1.1 vegur
connect-time: 0
x-request-start: 1565785161631
#total-route-time: 0
#content-length: 2653
timestamp: 1565785161636

{
  "action": "created",
  "installation": {
    "id": 1500958,
    "account": {
      "login": "VeryBigCompany",
      "id": 22247092,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjIyMjQ3MDky",
      "avatar_url": "https://avatars2.githubusercontent.com/u/22247092?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/VeryBigCompany",
      "html_url": "https://github.com/VeryBigCompany",
      "followers_url": "https://api.github.com/users/VeryBigCompany/followers",
      "following_url": "https://api.github.com/users/VeryBigCompany/following{/other_user}",
      "gists_url": "https://api.github.com/users/VeryBigCompany/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/VeryBigCompany/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/VeryBigCompany/subscriptions",
      "organizations_url": "https://api.github.com/users/VeryBigCompany/orgs",
      "repos_url": "https://api.github.com/users/VeryBigCompany/repos",
      "events_url": "https://api.github.com/users/VeryBigCompany/events{/privacy}",
      "received_events_url": "https://api.github.com/users/VeryBigCompany/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "repository_selection": "selected",
    "access_tokens_url": "https://api.github.com/app/installations/1500958/access_tokens",
    "repositories_url": "https://api.github.com/installation/repositories",
    "html_url": "https://github.com/organizations/VeryBigCompany/settings/installations/1500958",
    "app_id": 38266,
    "target_id": 22247092,
    "target_type": "Organization",
    "permissions": {
      "contents": "read",
      "metadata": "read"
    },
    "events": [
      "create",
      "delete",
      "label",
      "push",
      "release",
      "repository"
    ],
    "created_at": 1565777903,
    "updated_at": 1565777903,
    "single_file_name": null
  },
  "repositories": [
    {
      "id": 201464761,
      "node_id": "MDEwOlJlcG9zaXRvcnkyMDE0NjQ3NjE=",
      "name": "vbc-fork-intro-coroutines",
      "full_name": "VeryBigCompany/vbc-fork-intro-coroutines",
      "private": false
    }
  ],
  "sender": {
    "login": "2Pit",
    "id": 11159462,
    "node_id": "MDQ6VXNlcjExMTU5NDYy",
    "avatar_url": "https://avatars3.githubusercontent.com/u/11159462?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/2Pit",
    "html_url": "https://github.com/2Pit",
    "followers_url": "https://api.github.com/users/2Pit/followers",
    "following_url": "https://api.github.com/users/2Pit/following{/other_user}",
    "gists_url": "https://api.github.com/users/2Pit/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/2Pit/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/2Pit/subscriptions",
    "organizations_url": "https://api.github.com/users/2Pit/orgs",
    "repos_url": "https://api.github.com/users/2Pit/repos",
    "events_url": "https://api.github.com/users/2Pit/events{/privacy}",
    "received_events_url": "https://api.github.com/users/2Pit/received_events",
    "type": "User",
    "site_admin": false
  }
}

###

GET https://api.github.com/projects/columns/6215563/cards
Accept: application/vnd.github.inertia-preview+json
Authorization: token 147d2090ec01f251b04912916f14d4ce3646b5b7

###

GET https://api.github.com/projects/columns/cards/25238393
Accept: application/vnd.github.inertia-preview+json
Authorization: token 147d2090ec01f251b04912916f14d4ce3646b5b7

###

GET https://api.github.com/projects/columns/cards/25238393
Accept: application/vnd.github.inertia-preview+json
Accept: application/vnd.github.v3+json
Authorization: token 147d2090ec01f251b04912916f14d4ce3646b5b7

###

GET https://api.github.com/repos/ksamples/main/issues
Authorization: token 147d2090ec01f251b04912916f14d4ce3646b5b7
Accept: application/vnd.github.v3+json

###



