# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://0.0.0.0:8090/

###
GET http://0.0.0.0:8090/samples/1

###

GET http://0.0.0.0:8090/samples/?ids=1&ids=2

###

GET http://0.0.0.0:8090/branches/?after_id=1

###

GET http://0.0.0.0:8090/jobs/?processId=1

###

POST http://0.0.0.0:8090/add/
Content-Type: application/json

{
  "owner": "spekframework",
  "repo":"spek",
  "branch": "master",
  "path":"samples/jvm/",
  "name": "spek_jvm"
}

###
POST http://0.0.0.0:8090/test/branch
Content-Type: application/json

{
  "id": 10,
  "repoId": 20,
  "name": "NAME",
  "sha": "SHA"
}

###



